name: Push to Dockerhub

on:
  push:
    branches:
      - main

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t fluid-builder -f Dockerfile .

      - name: Tag Docker image as latest
        run: docker tag fluid-builder maifeeulasad/fluid-builder:latest

      - name: Push Docker image to Docker Hub
        run: docker push maifeeulasad/fluid-builder:latest
